# Generated by Django 4.2 on 2024-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('is_merried', models.BooleanField()),
            ],
        ),
    ]
